config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'home#welcome'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 3, maximum: 100}
    validates :description, presence: true, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
  <div class="errors-container">
    <div id="error_explanation">
      <h2 class="text-center text-danger p5"><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <div class="errors-values bg-danger">
         <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      </div>
     
    </div>
  </div>
    
  <% end %>
<div class="form-container">
  <div class="field">
    <%= form.label :title %> <br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %> <br>
    <%= form.text_area :description, rows: "15" %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-success" %>
  </div>
</div>
  
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-center">Editing Article</h1>

<%= render 'form', article: @article %>

<div class="container text-center mx-auto">
<%= link_to 'Show', @article, class: "btn btn-success text-center" %> |
<%= link_to 'Back', articles_path,  class: "btn btn-primary text-center"%>
</div>

app/views/articles/index.html.erb
<h2 class="list-title text-uppercase text-center p5 text-success font-size-large">list of Articles</h2>


<div class="container">
  
  <p id="notice" class="text-center font-size-large text-danger"><%= notice %></p> 
  <div class="list-container mx-auto">
    <% @articles.each do |article| %>
    <div class="list-card">
      <h3 class="list-article-title text-center p5">
        <%= link_to "#{article.title}", article, class: "text-center text-uppercase"%>
      </h3>
      <p class="list-article-description">
        <%= truncate(article.description,  length: 100) %>
      </p>
      <div class="list-btn">
        <td><%= link_to 'Edit', edit_article_path(article), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', article, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </div>
    </div>
 
  <% end %>
  <hr>
  <%= link_to 'New Article', new_article_path, class: 'btn btn-success' %>
     </div>
    
  </div>
 

app/views/articles/new.html.erb
<div class="container">
    <h1 class="text-center p5">Create New Article</h1>

    <%= render 'form', article: @article %>

    <%= link_to 'Back', articles_path, class: "btn btn-primary" %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <p id="notice" class="text-center text-success font-size-large"><%= notice %></p>

  <div class="show-container">
    <p class="py-medium">
      <strong class="show-title font-size-large">Title:</strong>
      <%= link_to "#{@article.title}", article_path(@article), class: "font-size-large text-uppercase" %>
    </p>
    
    <p>
      <strong class="show-description">Description:</strong>
      <%= @article.description %>
    </p>
    
    
    
  </div>
  <div class="show-button-container">
    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-success" %> |
  <%= link_to 'Back', articles_path, class: "btn btn-primary"%>
  </div>
  
</div>

app/views/home/about.html.erb
<div class="container">
    <div class="about-container">
        <div class="img-container">
            <img src="assets/images/profilepic.jpg" alt="">
        </div>
        <div class="about-author-name">Kekeli Dogbevi Jiresse</div>
    </div>
    <h2 class="text-center text-uppercase p5">Write to Us</h2>
    <p class="about-paragragh">
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloribus, nobis! Quis, molestiae vitae adipisci
        repellendus cupiditate molestias facilis atque labore, ut assumenda iusto veniam! Culpa vitae libero deserunt
        nulla qui in eos, assumenda quas eaque magni repellat aut autem corporis voluptatibus ullam soluta id. Ut sed
        nostrum quibusdam aspernatur magni facilis vero fugit harum, necessitatibus repudiandae sunt atque illo. Non ex
        nihil, enim labore culpa qui dignissimos adipisci vitae veritatis id necessitatibus beatae voluptas maiores,
        accusamus eaque. Ducimus consequuntur corporis alias nostrum blanditiis suscipit excepturi, vel est vero,
        corrupti voluptates libero id, temporibus fugiat! Aliquam perspiciatis doloribus reiciendis voluptas minus fugit
        ipsam animi, assumenda, laborum placeat voluptatibus consectetur repellendus quasi iste cum adipisci magnam
        eaque illo quam amet officia! Debitis explicabo similique hic expedita, magni ducimus nisi? Veniam doloremque
        adipisci dicta iure ullam sequi culpa, totam, repellat expedita illo cumque aliquam vero ea dolorum distinctio
        inventore tempora? Itaque esse in saepe nobis. Consequuntur vel sed sapiente mollitia repellendus tempora
        nostrum in voluptates eaque ut blanditiis, animi ipsa ab vero et optio deleniti accusantium inventore suscipit
        molestiae porro dolorem fuga. Sapiente non sequi repellat exercitationem reprehenderit delectus ullam? Voluptate
        incidunt eos veniam, minima pariatur ratione dolorum id architecto debitis nostrum alias esse cum repellendus!
        Reiciendis iusto suscipit debitis excepturi! Neque vel modi earum recusandae sint consectetur cum maiores
        accusantium ad explicabo. Ex nam cumque est illum aliquid distinctio, dolore rem. Earum tempore harum fugiat
        illum nobis suscipit tenetur ipsam vitae quidem recusandae, distinctio delectus eligendi asperiores enim aliquam
        adipisci quam. Dicta vero consequatur, possimus quaerat aperiam a rerum impedit libero sed. Nemo sequi odio
        magni laborum tempora ipsam numquam id provident veritatis, possimus doloremque earum culpa rerum natus
        similique nihil et repellat velit. Non numquam veniam sequi deleniti reprehenderit mollitia, obcaecati est,
        optio voluptatum repellat aliquam possimus. Non excepturi numquam temporibus nesciunt consectetur, quaerat
        molestias aspernatur amet fugit at nobis commodi, incidunt laboriosam ex autem? Quibusdam nesciunt laboriosam
        provident earum, molestias neque vitae impedit aliquid beatae quasi tempore ducimus porro similique dolorum
        recusandae? Consectetur sapiente dolorem, mollitia eligendi vero magnam at debitis autem possimus, quos ratione
        dolore aut eaque dolor odit vitae, fuga perspiciatis nobis rerum sed impedit error velit? Impedit, unde.
        Blanditiis voluptas distinctio vel doloribus culpa maiores, accusamus magni omnis deserunt officia perferendis
        aliquid assumenda quisquam iusto qui possimus quaerat accusantium harum! Ipsa dolor pariatur, quasi sapiente at
        quo suscipit, nostrum similique cum aperiam, alias tempore perspiciatis soluta incidunt? Repellat illum sapiente
        veniam quisquam deserunt harum iusto modi ut ipsam est alias, pariatur molestias ex reiciendis? Doloribus
        nesciunt laboriosam, esse, ullam, excepturi ad repudiandae amet alias quo vitae veritatis sint iure? Qui
        consequuntur esse, ipsa animi earum dicta deleniti eligendi eaque aspernatur? Eligendi labore fugiat enim
        possimus et atque provident? Quas magni maxime rem repudiandae suscipit ducimus cupiditate corporis aspernatur
        aliquid ullam eaque quasi cum, dolore animi expedita inventore facere? Sequi voluptates pariatur impedit soluta
        aliquam! Nulla, eos cumque! Possimus laudantium esse, saepe accusamus beatae sed earum eos eius optio ipsa,
        commodi autem vitae? Odit qui nam dolor ex, aliquid ipsam quasi incidunt soluta recusandae voluptatem, molestiae
        maiores minus, ullam illo architecto non hic ipsa nostrum fugit! Nostrum quod sunt iste minus corporis possimus
        voluptas nihil est blanditiis libero porro voluptate corrupti eveniet reprehenderit vel animi laborum harum,
        quasi natus autem. Atque sed assumenda iure excepturi possimus architecto facere quia? Fugit architecto quam eos
        ratione, ipsum quae numquam enim eius alias sapiente temporibus minima debitis vero amet deserunt quaerat
        molestiae. Distinctio laborum, quasi atque accusantium nihil, qui ratione eos necessitatibus et officia
        dignissimos! Iure temporibus omnis quos cumque laboriosam odit modi adipisci placeat nisi fuga. Consequatur et
        ex repellendus?
    </p>
</div>

app/views/home/welcome.html.erb
<div class="container">
    <div class="jumbo-centers jumbo-centers-img">
        <h3 class="text-center text-uppercase font-weight-bolder font-size-large text-white p5">The linux Journal</h3>
        <a href="#" class="btn btn-success text-uppercase">Sign up to the newsletter</a>
    </div>
    <h4 class="p5 text-center font-size-large">Lorem ipsum dolor sit amet consectetur</h4>
    <p class="fill">
         adipisicing elit. Animi ullam facere eaque velit ipsum hic totam vitae
        quas? Natus corporis, tempore autem nihil eveniet odit, dignissimos fugit non laboriosam perspiciatis, tenetur
        rem? Fugit id sit quisquam cumque provident vel, iste totam fugiat! Temporibus dolores tempore numquam quo
        officia cum quod, ducimus, earum aspernatur, ea voluptas. Expedita, doloribus perferendis! Perferendis quo nihil
        vitae soluta consectetur, sed adipisci aliquid reiciendis autem porro id libero laboriosam distinctio. Possimus
        tenetur eius facilis repellat animi accusamus, voluptatem tempore fugiat perferendis architecto mollitia
        quibusdam repudiandae quia! Provident labore molestias delectus dicta nam voluptate a quia aspernatur odit, non
        corrupti, veniam nisi expedita explicabo! Sed doloremque temporibus distinctio cupiditate molestiae, rem sit
        magnam quas blanditiis inventore labore voluptatem vel amet omnis, aspernatur quis porro laudantium consequatur
        eaque. Explicabo quibusdam animi maiores doloremque enim sint magnam cum reiciendis numquam consequatur tenetur,
        saepe architecto! Incidunt beatae deleniti inventore alias explicabo quisquam ipsam sunt necessitatibus
        reiciendis sed. Provident ea eius nulla natus earum laudantium dignissimos magni rerum illo impedit optio,
        architecto ipsum consequatur expedita dolores consectetur dicta fugit iusto, ratione nobis, ipsa beatae. Libero
        quis dolores vitae, rem repellat aliquam impedit, earum velit molestias, mollitia quibusdam modi ab. Sint, ipsa.
    </p>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <p class="copy">
            <%= link_to 'The Linux Foundation', root_path, class: "text-uppercase copy-link px-small text-white font-size-medium"%>

        </p>
            <ul class="nav_ul">
                <li class="nav-li">
                    <%= link_to 'Home', root_path, class: "nav-link text-white"%>
                </li>
                <li class="nav-li">
                    <%= link_to 'Blog', articles_path, class: "nav-link text-white"%>
                </li>
                <li class="nav-li">
                    <%= link_to 'About', home_about_path, class: "nav-link text-white"%>
                </li>
            </ul>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="nav p4">
    <h1 class="nav-brand px-small">
        <%= link_to 'The Linux Foundation', root_path, class: "nav-brand-link text-uppercase  text-white font-size-large"%>
    </h1>

    <ul class="nav_ul">
        <li class="nav-li">
            <%= link_to 'Home', root_path, class: "nav-link text-white"%>
        </li>
        <li class="nav-li">
            <%= link_to 'Blog', articles_path, class: "nav-link text-white"%>
        </li>
        <li class="nav-li">
            <%= link_to 'About', home_about_path, class: "nav-link text-white"%>
        </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Linux Journal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>